
version: 0.2

env:
  shell: bash
  variables:
    FUNCTION_NAME: 
    URL:

phases:
  install:
    commands:
      - python3 -m venv local
      - . ./local/bin/activate
      - make requirements

  pre_build:
    commands:
      - . ./local/bin/activate
      - make check lint
      - make test

  build:
    commands:
      - make build

  post_build:
    commands:
      - make deploy PLATFORM="AWS CodeBuild" FUNCTION=$FUNCTION_NAME VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER
      - make testdeployment URL=$URL VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - 'lambda.zip'