
version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: "<your_AWS_access_key>"
    AWS_SECRET_ACCESS_KEY: "<your_AWS_secret_key>"
    AWS_DEFAULT_REGION: "<your_AWS_region>"
    STAGING_FUNCTION_NAME: "<your_staging_function_name>"
    STAGING_URL: "<your_staging_url>"
    PRODUCTION_FUNCTION_NAME: "<your_production_function_name>"
    PRODUCTION_URL: "<your_production_url>"

phases:
  install:
    commands:
      - python3 -m venv local
      - . ./local/bin/activate
      - make requirements

  pre_build:
    commands:
      - . ./local/bin/activate
      - make check lint
      - make test

  build:
    commands:
      - make build

  post_build:
    commands:
      - make deploy PLATFORM="AWS CodeBuild" FUNCTION=$STAGING_FUNCTION_NAME VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - 'lambda.zip'
