pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'replace-with-your-region'
        STAGING_FUNCTION_NAME = 'replace-with-your-function-name-staging'
        STAGING_URL           = 'https://replace-with-your-staging-url.lambda-url.REGION.on.aws'
        PRODUCTION_FUNCTION_NAME = 'replace-with-your-function-name-production'
        PRODUCTION_URL = 'https://replace-with-your-production-url.lambda-url.REGION.on.aws'
    }

    stages {
        stage('Requirements') {
            steps {
                sh('''#!/bin/bash
                        python3 -m virtualenv local
                        . ./local/bin/activate
                        make requirements
                        ''')
            }
        }
        stage('Check') {
            parallel {
                stage('Check:Lint') {
                    steps {
                        sh('''#!/bin/bash
                                . ./local/bin/activate
                                flake8 --ignore=E501,E231 *.py tests/*.py
                                pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
                                ''')
                    }
                }
                stage('Check-Lint-Test') {
                    steps {
                        sh('''#!/bin/bash
                                    . ./local/bin/activate
                            make check lint test
                                ''')
                    }
                }
            }
        }
        stage('Build') {
            steps {
                sh('''#!/bin/bash
                        . ./local/bin/activate
                        ./upload-new-version.sh
                        ''')
            }
        }
        stage('Deploy Staging') {
            steps {
                sh('''#!/bin/bash
                        . ./local/bin/activate
                        ./deploy-new-version.sh staging
                        ''')
            }
        }
        stage('Test Staging') {
            steps {
                sh('''#!/bin/bash
                        . ./local/bin/activate
                        ./test-environment.sh staging
                        ''')
            }
        }
        stage('Deploy Production') {
            steps {
                sh('''#!/bin/bash
                        . ./local/bin/activate
                        ./deploy-new-version.sh production
                        ''')
            }
        }
        stage('Test Production') {
            steps {
                sh('''#!/bin/bash
                        . ./local/bin/activate
                        ./test-environment.sh production
                        ''')
            }
        }
    }
}
