trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Check
  jobs:
  - job: BuildJob
    steps:
    - script: |
        python3 -m venv local
        source ./local/bin/activate
        make requirements
      displayName: 'Requirements'

    - script: |
        source ./local/bin/activate
        make check lint
      displayName: 'Check:Lint'

    - script: |
        source ./local/bin/activate
        make test
      displayName: 'Check:Test'

- stage: DeployStaging
  jobs:
  - job: StagingDeployment
    steps:
    - checkout: self

    - script: |
        make build
      displayName: 'Build'

    - script: |
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
        make deploy PLATFORM="Azure DevOps" FUNCTION=$(STAGING_FUNCTION_NAME) VERSION=$(Build.SourceVersion) BUILD_NUMBER=$(Build.BuildNumber)
      displayName: 'Deploy Staging'

    - script: |
        make testdeployment URL=$(STAGING_URL) VERSION=$(Build.SourceVersion)
      displayName: 'Test Staging'

- stage: DeployProduction
  jobs:
  - job: ProductionDeployment
    steps:
    - checkout: self

    - script: |
        make build
      displayName: 'Build'

    - script: |
        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
        make deploy PLATFORM="Azure DevOps" FUNCTION=$(PRODUCTION_FUNCTION_NAME) VERSION=$(Build.SourceVersion) BUILD_NUMBER=$(Build.BuildNumber)
      displayName: 'Deploy Production'

    - script: |
        make testdeployment URL=$(PRODUCTION_URL) VERSION=$(Build.SourceVersion)
      displayName: 'Test Production'
