---
version: 2
plan:
  project-key: EP
  key: BUIL
  name: Build
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: false
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        python3 -m venv local
        . ./local/bin/activate
        make requirements
      description: Requirements
  - script:
      interpreter: SHELL
      scripts:
      - |-
        . ./local/bin/activate
        make check lint test
      description: Check-Lint-Test
  - command:
      executable: Make
      argument: clean build
      description: Build
  - command:
      executable: Make
      argument: deploy ENVIRONMENT="Staging" PLATFORM="Bamboo" FUNCTION=${bamboo.STAGING_FUNCTION_NAME} VERSION=${bamboo.planRepository.revision} BUILD_NUMBER=${bamboo.buildNumber}
      envrionment: AWS_ACCESS_KEY_ID=${bamboo.AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${bamboo.AWS_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${bamboo.AWS_DEFAULT_REGION}
      description: Deploy Staging
  - command:
      executable: Make
      argument: testdeployment URL=${bamboo.STAGING_URL}
      description: Test Staging
  - command:
      executable: Make
      argument: deploy ENVIRONMENT="Production" PLATFORM="Bamboo" FUNCTION=${bamboo.PRODUCTION_FUNCTION_NAME} VERSION=${bamboo.planRepository.revision} BUILD_NUMBER=${bamboo.buildNumber}
      envrionment: AWS_ACCESS_KEY_ID=${bamboo.AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${bamboo.AWS_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${bamboo.AWS_DEFAULT_REGION}
      description: Deploy Production
  - command:
      executable: Make
      argument: testdeployment URL=${bamboo.PRODUCTION_URL}
      description: Test Production
  artifacts:
  - name: Zip File
    location: .
    pattern: '**/*.zip'
    shared: true
    required: true
  artifact-subscriptions: []
variables:
  AWS_ACCESS_KEY_ID: UPDATE_THIS_VALUE
  AWS_DEFAULT_REGION: UPDATE_THIS_VALUE
  AWS_SECRET_ACCESS_KEY: UPDATE_THIS_VALUE
  PRODUCTION_FUNCTION_NAME: UPDATE_THIS_VALUE
  PRODUCTION_URL: UPDATE_THIS_VALUE
  STAGING_FUNCTION_NAME: UPDATE_THIS_VALUE
  STAGING_URL: UPDATE_THIS_VALUE
repositories:
- repo:
    scope: global
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
